In [1]:
import warnings
warnings.filterwarnings("ignore")
import shutil
import os

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from tqdm import tqdm

**Reference to extract Unigrams from byte file:** https://github.com/skshashankkumar41/Microsoft-Malware-Detection/blob/master/Microsoft_Malware_Detection.ipynb

In [4]:
# Removing Address from Byte File and converting it to a text file.

files = os.listdir("C:/UMBC/606 Capstone/Data/train/byte_files/")

for file in tqdm(files):
    if(file.endswith("bytes")):
        file=file.split('.')[0]
        text_file = open('C:/UMBC/606 Capstone/Data/train/1 Byte Files/' + file + ".txt", 'w+')
        with open('C:/UMBC/606 Capstone/Data/train/byte_files/' + file + ".bytes","r") as fp:
            for line in fp:
                a=line.rstrip().split(" ")[1:]
                b=' '.join(a)
                b=b+"\n"
                text_file.write(b)
            fp.close()
        text_file.close()

In [3]:
files = os.listdir('C:/UMBC/606 Capstone/Data/train/1 Byte Files/')
feature_matrix = np.zeros((len(files),257),dtype=int)
k=0


#program to convert into bag of words of bytefiles
#this is custom-built bag of words this is unigram bag of words
unigrams = open('C:/UMBC/606 Capstone/Data/train/unigram.csv','w+')
unigrams.write("ID,0,1,2,3,4,5,6,7,8,9,0a,0b,0c,0d,0e,0f,10,11,12,13,14,15,16,17,18,19,1a,1b,1c,1d,1e,1f,20,21,22,23,24,25,26,27,28,29,2a,2b,2c,2d,2e,2f,30,31,32,33,34,35,36,37,38,39,3a,3b,3c,3d,3e,3f,40,41,42,43,44,45,46,47,48,49,4a,4b,4c,4d,4e,4f,50,51,52,53,54,55,56,57,58,59,5a,5b,5c,5d,5e,5f,60,61,62,63,64,65,66,67,68,69,6a,6b,6c,6d,6e,6f,70,71,72,73,74,75,76,77,78,79,7a,7b,7c,7d,7e,7f,80,81,82,83,84,85,86,87,88,89,8a,8b,8c,8d,8e,8f,90,91,92,93,94,95,96,97,98,99,9a,9b,9c,9d,9e,9f,a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,aa,ab,ac,ad,ae,af,b0,b1,b2,b3,b4,b5,b6,b7,b8,b9,ba,bb,bc,bd,be,bf,c0,c1,c2,c3,c4,c5,c6,c7,c8,c9,ca,cb,cc,cd,ce,cf,d0,d1,d2,d3,d4,d5,d6,d7,d8,d9,da,db,dc,dd,de,df,e0,e1,e2,e3,e4,e5,e6,e7,e8,e9,ea,eb,ec,ed,ee,ef,f0,f1,f2,f3,f4,f5,f6,f7,f8,f9,fa,fb,fc,fd,fe,ff,??")
unigrams.write("\n")
for file in tqdm(files):
    unigrams.write(file+",")
    if(file.endswith("txt")):
        with open('C:/UMBC/606 Capstone/Data/train/1 Byte Files/'+file,"r") as byte_file:
            for lines in byte_file:
                line=lines.rstrip().split(" ")
                for hex_code in line:
                    if hex_code=='??':
                        feature_matrix[k][256]+=1
                    else:
                        feature_matrix[k][int(hex_code,16)]+=1
        byte_file.close()
    for i in feature_matrix[k]:
        unigrams.write(str(i)+",")
    unigrams.write("\n")
    
    k += 1

unigrams.close()

100%|██████████████████████████████████████████████████████████████████████████| 10868/10868 [3:40:55<00:00,  1.22s/it]

In [6]:
unigrams_df = pd.read_csv("C:/UMBC/606 Capstone/Data/train/unigram.csv")
unigrams_df.head()

,ID,0,1,2,3,4,5,6,7,8,...,f7,f8,f9,fa,fb,fc,fd,fe,ff,??
01azqd4InC7m9JpocGv5.txt,601905,3905,2816,3832,3345,3242,3650,3201,2965,3205,...,3687,3101,3211,3097,2758,3099,2759,5753,1824,NaN
01IsoiSMh5gxyDYTl4CB.txt,39755,8337,7249,7186,8663,6844,8420,7589,9291,358,...,6536,439,281,302,7639,518,17001,54902,8588,NaN
01jsnpXSAlgw6aPeDxrU.txt,93506,9542,2568,2438,8925,9330,9007,2342,9107,2457,...,2358,2242,2885,2863,2471,2786,2680,49144,468,NaN
01kcPWA9K2BOxQeS5Rju.txt,21091,1213,726,817,1257,625,550,523,1078,473,...,873,485,462,516,1133,471,761,7998,13940,NaN
01SuzwMJEIXsK7A8dQbl.txt,19764,710,302,433,559,410,262,249,422,223,...,947,350,209,239,653,221,242,2199,9008,NaN

In [14]:
uni = pd.read_csv("C:/UMBC/606 Capstone/Data/train/unigram.csv", index_col=False)
uni.head()

,ID,0,1,2,3,4,5,6,7,8,...,f7,f8,f9,fa,fb,fc,fd,fe,ff,??
0,01azqd4InC7m9JpocGv5.txt,601905,3905,2816,3832,3345,3242,3650,3201,2965,...,2804,3687,3101,3211,3097,2758,3099,2759,5753,1824
1,01IsoiSMh5gxyDYTl4CB.txt,39755,8337,7249,7186,8663,6844,8420,7589,9291,...,451,6536,439,281,302,7639,518,17001,54902,8588
2,01jsnpXSAlgw6aPeDxrU.txt,93506,9542,2568,2438,8925,9330,9007,2342,9107,...,2325,2358,2242,2885,2863,2471,2786,2680,49144,468
3,01kcPWA9K2BOxQeS5Rju.txt,21091,1213,726,817,1257,625,550,523,1078,...,478,873,485,462,516,1133,471,761,7998,13940
4,01SuzwMJEIXsK7A8dQbl.txt,19764,710,302,433,559,410,262,249,422,...,847,947,350,209,239,653,221,242,2199,9008